#!/usr/bin/env bash
set -euo pipefail

MARLOWE_HOME="${MARLOWE_HOME:-$HOME/.marlowe}"
MARLOWE_FRAMEWORK="${MARLOWE_FRAMEWORK:-$HOME/.marlowe-framework}"
OUT_DIR="$MARLOWE_HOME/generated"
OUT="$OUT_DIR/cursor-rules.md"

mkdir -p "$OUT_DIR"

{
  echo "<!-- generated by marlowe; do not edit. source: ~/.marlowe/preferences.md + memory.md -->"
  MARLOWE_HOME="$MARLOWE_HOME" "$MARLOWE_FRAMEWORK/adapters/common/render.sh"
} > "$OUT"

cat <<EOF
[marlowe/cursor] rendered rules -> $OUT

To apply in Cursor:
  1. open Cursor → Settings (Cmd/Ctrl + ,)
  2. search "Rules for AI"
  3. paste the content of $OUT
  4. re-run 'marlowe sync' after editing ~/.marlowe/preferences.md, then paste again
EOF
