#!/usr/bin/env bash
set -euo pipefail

# Cursor has no stable user-scoped rules path we can safely auto-edit on Linux.
# v0.2 strategy: render preferences into a copy-pasteable file and tell the user.
# v0.3 will add a project-scoped mode: `marlowe apply cursor <project-dir>`
# writing .cursor/rules/marlowe.mdc.

MARLOWE_HOME="${MARLOWE_HOME:-$HOME/.marlowe}"
SRC="$MARLOWE_HOME/preferences.md"
OUT_DIR="$MARLOWE_HOME/generated"
OUT="$OUT_DIR/cursor-rules.md"

[ -f "$SRC" ] || { echo "no preferences.md at $SRC" >&2; exit 1; }
mkdir -p "$OUT_DIR"

{
  echo "<!-- generated by marlowe; do not edit. source: ~/.marlowe/preferences.md -->"
  cat "$SRC"
} > "$OUT"

cat <<EOF
[marlowe/cursor] rendered rules -> $OUT

To apply in Cursor:
  1. open Cursor → Settings (Cmd/Ctrl + ,)
  2. search "Rules for AI"
  3. paste the content of $OUT
  4. re-run 'marlowe sync' after editing ~/.marlowe/preferences.md, then paste again
EOF
