#!/usr/bin/env bash
set -euo pipefail

MARLOWE_HOME="${MARLOWE_HOME:-$HOME/.marlowe}"
MARLOWE_FRAMEWORK="${MARLOWE_FRAMEWORK:-$HOME/.marlowe-framework}"
OUT_DIR="$MARLOWE_HOME/generated"
OUT="$OUT_DIR/cursor-rules.md"

mkdir -p "$OUT_DIR"

{
  echo "<!-- generated by marlowe; do not edit. source: ~/.marlowe/preferences.md + memory.md -->"
  MARLOWE_HOME="$MARLOWE_HOME" "$MARLOWE_FRAMEWORK/adapters/common/render.sh"
} > "$OUT"

echo "[marlowe/cursor] rendered rules -> $OUT"

# Cursor's User Rules are UI-stored, not file-based. Best we can do is make
# the paste step painless by pre-filling the clipboard.
COPIED=""
if   command -v wl-copy  >/dev/null 2>&1; then wl-copy  < "$OUT" && COPIED="wl-copy"
elif command -v xclip    >/dev/null 2>&1; then xclip -selection clipboard < "$OUT" && COPIED="xclip"
elif command -v xsel     >/dev/null 2>&1; then xsel --clipboard --input  < "$OUT" && COPIED="xsel"
elif command -v pbcopy   >/dev/null 2>&1; then pbcopy   < "$OUT" && COPIED="pbcopy"
elif command -v clip.exe >/dev/null 2>&1; then clip.exe < "$OUT" && COPIED="clip.exe"
fi

if [ -n "$COPIED" ]; then
  echo "[marlowe/cursor] copied to clipboard ($COPIED) — ready to paste"
else
  echo "[marlowe/cursor] no clipboard tool (wl-copy/xclip/xsel/pbcopy/clip.exe) — copy manually"
fi

cat <<EOF

To apply in Cursor:
  1. open Cursor → Settings (Cmd/Ctrl + ,)
  2. search "Rules for AI"
  3. paste${COPIED:+ (clipboard is ready)}
  4. re-run 'marlowe apply cursor' after editing preferences.md, then paste again
EOF
